; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = battery-wokwi
extra_configs = secret_values.ini

[base]
    framework = arduino
    platform = espressif32
    board = seeed_xiao_esp32c3
    board_build.partitions = partion_table.csv
    monitor_speed = 115200

    lib_deps =
        ArduinoJson
        https://github.com/RobTillaart/INA226
        https://github.com/olikraus/U8g2_Arduino
        https://github.com/GyverLibs/EncButton
        https://github.com/me-no-dev/ESPAsyncWebServer
        https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino

    build_unflags =
        -std=gnu++11

    build_flags =
        ${secrets.build_flags}
        -std=c++17
        -std=gnu++17

        ; Hardware
        '-D BUZZER_PIN = D10'
        '-D BUTTONS_PIN = D2'
        '-D OLED_PWR_PIN = D9'
        '-D OLED_SCL = D5'
        '-D OLED_SDA = D4'
        
        ; Настройки сети
        '-D TZ_INFO="UTC3"'
        '-D HOSTNAME="https://rtuitlab.dev/"'
        -D PORT=80
        '-D INFLUXDB_URL="http://82.97.246.60:8086"'
        '-D INFLUXDB_ORG="a9a0c23e8f3b54db"'
        '-D INFLUXDB_BUCKET="batteries"'

        ; Настройки параметров
        '-D SETTINGS_SPACE_NAME="pref"'

        ; Прочие настройки
        -D ASYNCWEBSERVER_REGEX=1
        -D CORE_DEBUG_LEVEL=0 ; Для отключение логов
        

[env:test_board]
    extends = base
    build_type = debug

    build_unflags =
        ${base.build_unflags}

    build_flags = 
        ${base.build_flags}
        -D ID=3
        
        -D WOKWI


[env:battery-old]
    extends = base
    build_type = debug

    build_unflags =
        ${base.build_unflags}

    build_flags = 
        ${base.build_flags}
        -D ID=4


[env:battery-wokwi]
    extends = base
    build_type = debug

    build_unflags =
        ${base.build_unflags}

    build_flags = 
        ${base.build_flags}
        -D ID=1

        ; Hardware
        -D WITH_DISPLAY
        -D WOKWI

        ; Настройки сети
        '-D WIFI_SSID="Wokwi-GUEST"'
        '-D WIFI_PASSWORD=""'

[env:battery-debug]
    extends = base
    build_type = debug
    monitor_filters = esp32_exception_decoder

    build_unflags =
        ${base.build_unflags}

    build_flags = 
        ${base.build_flags}
        -D ID=1
        -w

        ; Hardware
        -D WITH_DISPLAY

[env:battery]
    extends = base
    build_type = release

    build_unflags =
        ${base.build_unflags}

    build_flags = 
        ${base.build_flags}
        -D ID=1
        -w

        ; Hardware
        -D WITH_DISPLAY
